import type { User, Review, Book } from './types';

export const users: User[] = [
  {
    id: 'user1',
    name: 'Jane Doe',
    email: 'jane.doe@example.com',
    bio: 'Avid reader and coffee enthusiast. Lover of fantasy and historical fiction.',
    profileImage: 'avatar1',
    readingInterests: ['Fantasy', 'Historical Fiction', 'Mystery'],
    followers: 125,
    following: 88,
    role: 'reader',
  },
  {
    id: 'user2',
    name: 'John Smith',
    email: 'john.smith@example.com',
    bio: 'Sci-fi geek and part-time philosopher.',
    profileImage: 'avatar2',
    readingInterests: ['Science Fiction', 'Philosophy'],
    followers: 72,
    following: 150,
    role: 'reader',
  },
    {
    id: 'user3',
    name: 'Emily White',
    email: 'emily.white@example.com',
    bio: 'Librarian and lover of classic literature.',
    profileImage: 'avatar3',
    readingInterests: ['Classics', 'Poetry', 'Non-fiction'],
    followers: 210,
    following: 30,
    role: 'admin',
  },
];

export const reviews: Review[] = [
  {
    id: 'review1',
    bookId: 'book1',
    userId: 'user2',
    rating: 5,
    comment: "An absolute masterpiece of existential fiction. The concept is brilliant and the execution is flawless. A must-read!",
    likes: 15,
    createdAt: '2023-10-15',
  },
  {
    id: 'review2',
    bookId: 'book1',
    userId: 'user3',
    rating: 4,
    comment: "A thought-provoking and touching novel. I found some parts a bit slow, but the ending was incredibly satisfying.",
    likes: 8,
    createdAt: '2023-10-12',
  },
  {
    id: 'review3',
    bookId: 'book2',
    userId: 'user1',
    rating: 5,
    comment: "Hard sci-fi at its best! The science is fascinating, the characters are compelling, and the plot is a non-stop thrill ride.",
    likes: 22,
    createdAt: '2023-09-20',
  },
    {
    id: 'review4',
    bookId: 'book3',
    userId: 'user3',
    rating: 5,
    comment: "Ishiguro has done it again. A beautiful, haunting, and deeply moving story about what it means to be human.",
    likes: 18,
    createdAt: '2023-11-01',
  },
];

export const books: Book[] = [
  {
    id: 'book1',
    title: 'The Midnight Library',
    author: 'Matt Haig',
    coverImage: 'cover1',
    averageRating: 4.5,
    availability: 'Available',
    description: "Between life and death there is a library, and within that library, the shelves go on forever. Every book provides a chance to try another life you could have lived. To see how things would be if you had made other choices . . . Would you have done anything different, if you had the chance to undo your regrets?",
    reviews: reviews.filter(r => r.bookId === 'book1'),
    genre: 'Fantasy',
  },
  {
    id: 'book2',
    title: 'Project Hail Mary',
    author: 'Andy Weir',
    coverImage: 'cover2',
    averageRating: 4.8,
    availability: 'Checked Out',
    description: "Ryland Grace is the sole survivor on a desperate, last-chance mission—and if he fails, humanity and the earth itself will perish. Except that right now, he doesn’t know that. He can’t even remember his own name, let alone the nature of his assignment or how to complete it.",
    reviews: reviews.filter(r => r.bookId === 'book2'),
    genre: 'Science Fiction',
  },
  {
    id: 'book3',
    title: 'Klara and the Sun',
    author: 'Kazuo Ishiguro',
    coverImage: 'cover3',
    averageRating: 4.2,
    availability: 'Available',
    description: "The story of Klara, an Artificial Friend with outstanding observational qualities, who, from her place in the store, watches carefully the behavior of those who come in to browse, and of those who pass on the street outside. She remains hopeful a customer will soon choose her.",
    reviews: reviews.filter(r => r.bookId === 'book3'),
    genre: 'Science Fiction',
  },
  {
    id: 'book4',
    title: 'The Vanishing Half',
    author: 'Brit Bennett',
    coverImage: 'cover4',
    averageRating: 4.6,
    availability: 'Available',
    description: "The Vignes twin sisters will always be identical. But after growing up together in a small, southern black community and running away at age sixteen, it's not just the shape of their daily lives that is different as adults, it's everything: their families, their communities, their racial identities.",
    reviews: [],
    genre: 'Historical Fiction',
  },
  {
    id: 'book5',
    title: 'Dune',
    author: 'Frank Herbert',
    coverImage: 'cover5',
    averageRating: 4.9,
    availability: 'Available',
    description: "Set on the desert planet Arrakis, Dune is the story of the boy Paul Atreides, heir to a noble family tasked with ruling an inhospitable world where the only thing of value is the 'spice' melange, a drug capable of extending life and enhancing consciousness.",
    reviews: [],
    genre: 'Science Fiction',
  },
  {
    id: 'book6',
    title: 'The Four Winds',
    author: 'Kristin Hannah',
    coverImage: 'cover6',
    averageRating: 4.4,
    availability: 'Checked Out',
    description: "An epic novel of love and heroism and hope, set against the backdrop of one of America’s most defining eras—the Great Depression. Texas, 1934. Millions are out of work and a drought has broken the Great Plains.",
    reviews: [],
    genre: 'Historical Fiction',
  },
];
